### ISSUE TITLE
Remove mipmap and unwanted drawable resources related to app icon

### ISSUE THREAD

**Issue by rnkdsh** [ArchitGarg1/changa-lite#1]
It replaces the current app icon with default icon in this sdk. So please remove mipmap ad icon related resources from everywhere in the code.

**Comment by ArchitGarg1** [comment]
Please explain your concern in detail, How It is affecting you @rnkdsh? 

Code snippets or snapshots are welcome

**Comment by rnkdsh** [comment]
Please check the icon. It's been replaced by original icon after adding the SDK.

![Screenshot_20210119-130059.jpg](https://user-images.githubusercontent.com/16722278/105001954-8c273880-5a56-11eb-9fec-a43fe884974d.jpg)

**Comment by ArchitGarg1** [comment]
@rnkdsh try renaming your icon resource files if possible, I guess you are using **ic_launcher_foreground.xml**, right?

If this is the issue we'll fix this with the next update

**Comment by rnkdsh** [comment]
Yes, I am using that name.

**Comment by ArchitGarg1** [comment]
Did renaming the resource file fixed it for you? @rnkdsh

**Comment by rnkdsh** [comment]
Yes it worked.

**Comment by ArchitGarg1** [comment]
fixed in [v1.0.2](https://github.com/ArchitGarg1/changa-lite/tree/1.0.2)
